"""empty message

Revision ID: e00b1dd1a50a
Revises: 
Create Date: 2019-12-11 22:29:32.922739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e00b1dd1a50a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('myid', sa.String(length=48), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('myid')
    )
    op.create_table('Blocked_Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=48), nullable=False),
    sa.Column('blocked_user', sa.String(length=48), nullable=False),
    sa.ForeignKeyConstraint(['blocked_user'], ['users.myid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.myid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('active_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=48), nullable=False),
    sa.Column('request_sid', sa.String(length=120), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.myid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_sid')
    )
    op.create_table('authenticated_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=48), nullable=False),
    sa.Column('token', sa.String(length=48), nullable=True),
    sa.Column('last_time_checked', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.myid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authenticated_user')
    op.drop_table('active_users')
    op.drop_table('Blocked_Users')
    op.drop_table('users')
    # ### end Alembic commands ###
